### ISSUE TITLE
Problema configurazione comando ausiliario

### ISSUE THREAD

**Issue by nllptrx** [francesco-re-1107/openwebnet-alarm#1]
Buongiorno,
È da circa due giorni che sto cercando di capire come programmare il comando ausiliario sull'allarme 3486, solo che non capisco come fare. Mi può aiutare?

**Comment by francesco-re-1107** [comment]
Buongiorno,
Per impostare i comandi ausiliari deve entrare nella configurazione della centrale e poi seguire questi comandi:

- Antifurto 
- Automazioni
- Rinomina
- Memorizza 
- Evento 
- Codice OPEN

Nel caso avesse qualche dubbio provi anche a consultare il manuale ufficiale.
